name: bemilo
description: A new flutter project.
dependencies:
  flutter:
    sdk: flutter
  flutter_flux:
    git: git://github.com/flutter/flutter_flux.git
  pointycastle:
    git: git://github.com/bigflood/pointycastle.git
    
